# This file defines functions that:
#   1. create mutable matrix objects which can cache the inverse of the matrix.
#   2. Leverage the cache to optimize repeated calls to compute inverse

# Creates mutable matrix object that can cache its inverse
# 
# Args:
#  x:  inboud matrix that needs to be transformed
# 
# Returns:
#  A transformed matrix object as a list of functions
makeCacheMatrix <- function(x = matrix()) {
    m <- NULL;
    set <- function(m) {
        x <<- y
        m <<- NULL
    }
    get <- function() x
    setInverse <- function(xinverse) m <<- xinverse
    getInverse <- function() m
    list(set = set, 
         get = get, 
         setInverse = setInverse, 
         getInverse = getInverse)
}


# Tries to retrieve the inverse from cachce. If its a cache miss then calculates
# inverse and caches it.
# 
# Args:
# x: mutable matrix object generated by makeCacheMatrix function
# ...: additional parameters
# 
# Returns:
# Inverse of the matrix
cacheSolve <- function(x, ...) {
    m <- x$getInverse()
    if(!is.null(m)) {
        message("getting cached inverse")
        return(m)
    }
    data <- x$get()
    m <- solve(data)
    x$setInverse(m)
    m
}
